---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elephant-app
  labels:
    app: elephant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elephant-app
  template:
    metadata:
      labels:
        app: elephant-app
    spec:
      containers:
      - name: pandacloud-container
        image: 820242916511.dkr.ecr.us-east-1.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 3000
...
